name: Сборка AOSP и MIUI для Xiaomi 10
on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Кодовое имя устройства (например: cmi, lmi, umi)'
        required: true
        default: 'umi'
        type: choice
        options:
          - psyche
          - umi
          - munch
          - lmi
          - cmi
          - cas
          - apollo
          - alioth
          - elish
          - enuma
          - dagu
          - pipa
      nsu:
        description: 'Включить NextGenSU & SUSFS'
        required: true
        type: boolean
        default: true

jobs:
  build:
    name: Сборка ядра для ${{ inputs.device }}
    runs-on: ubuntu-latest

    steps:
    - name: Проверка источников
      uses: actions/checkout@v6
      with:
        fetch-depth: 1 # Для генерации номера версии необходима полная история коммитов

    - name: Очистка дискового пространства
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Установка зависимостей
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git curl wget bison flex zip bc cpio libssl-dev ccache python-is-python3
        sudo apt-get install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

    - name: Установка короткого коммита SHA
      id: vars
      run: |
        echo "sha=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Настройка кеша (ccache)
      uses: actions/cache@v5
      with:
        path: ~/.cache/ccache_mikernel
        key: ${{ runner.os }}-ccache-${{ inputs.device }}-${{ github.sha }}
        restore-keys: |
          kernel-ccache
          ${{ runner.os }}-ccache-${{ inputs.device }}-${{ inputs.device }} nsu-
          ${{ runner.os }}-${{ inputs.device }}-
          ${{ runner.os }}-ccache-

    - name: Установка Toolchain (ZyC-Clang 15)
      run: |
        mkdir -p $HOME/zyc-clang
        cd $HOME/zyc-clang
        wget -q https://github.com/ZyCromerZ/Clang/releases/download/15.0.7-20251111-release/Clang-15.0.7-20251111.tar.gz
        tar -zxvf Clang-15.0.7-20251111.tar.gz

    - name: Сборка ядра
      run: |
        chmod +x build.sh
        
        if [ "${{ inputs.ksu }}" == "true" ]; then
          echo "Building with NextGenSU..."
          bash build.sh ${{ inputs.device }} nsu
        else
          echo "Building without NextGenSU..."
          bash build.sh ${{ inputs.device }}
        fi

    - name: Выгрузка артефактов
      uses: actions/upload-artifact@v6
      with:
        name: aosp_miui-${{ inputs.device }}-${{ inputs.ksu && 'NSU' || 'NoNSU' }}
        path: ./
          AOSP_*.zip
          MIUI_*.zip
        if-no-files-found: error
    
    - name: Отображение структуры загруженных файлов
      run: ls -R
