name: Сборка AOSP и MIUI для Xiaomi 10
on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Выберите устройство'
        required: true
        default: 'umi'
        type: choice
        options:
          - psyche
          - umi
          - munch
          - lmi
          - cmi
          - cas
          - apollo
          - alioth
          - elish
          - enuma
          - dagu
          - pipa
      include_nsu:
        description: 'Включить NextGenSU & SUSFS в сборку?'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build:
    name: Сборка ядра для ${{ inputs.device }}
    runs-on: ubuntu-latest

    steps:
    - name: Проверка источников
      uses: actions/checkout@v6
      with:
        fetch-depth: 1 # Для генерации номера версии необходима полная история коммитов

    - name: Очистка дискового пространства
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Установка зависимостей
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git curl wget bison flex zip bc cpio libssl-dev ccache python-is-python3
        sudo apt-get install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

    - name: Установка короткого коммита SHA
      id: vars
      run: |
        echo "sha=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Настройка кеша (ccache)
      uses: actions/cache@v5
      with:
        path: |
          ~/.cache/ccache_nextgen
        key: ${{ runner.os }}-ccache-${{ github.event.inputs.device }}-${{ github.event.inputs.include_ksu }}-${{ steps.vars.outputs.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache-${{ github.event.inputs.device }}-${{ github.event.inputs.include_ksu }}-
          ${{ runner.os }}-ccache-${{ github.event.inputs.device }}-
          ${{ runner.os }}-ccache-

    - name: Установка Toolchain (ZyC-Clang 15)
      run: |
        mkdir -p $HOME/zyc-clang
        cd $HOME/zyc-clang
        wget -q https://github.com/ZyCromerZ/Clang/releases/download/15.0.7-20251111-release/Clang-15.0.7-20251111.tar.gz
        tar -zxvf Clang-15.0.7-20251111.tar.gz

    - name: Сборка ядра
      run: |
        if [ "${{ github.event.inputs.include_nsu }}" = "true" ]; then
          echo "Сборка c NextGenSU..."
          bash build.sh ${{ github.event.inputs.device }} nsu
        else
          echo "Сборка без NextGenSU..."
          bash build.sh ${{ github.event.inputs.device }}
        fi

    - name: Показать статистику кэширования
      run: ccache -s

    - name: Выгрузка артефактов
      uses: actions/upload-artifact@v6
      with:
        name: aosp_miui-${{ github.event.inputs.device }}${{ github.event.inputs.include_nsu == 'true' && '-nsu' || '' }}
        path: |
          AOSP_*.zip
          MIUI_*.zip
        if-no-files-found: error
    
    - name: Отображение структуры загруженных файлов
      run: ls -R
    - name: Установка текущей даты и короткого коммита SHA
      id: ids
      run: |
        echo "sha=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_OUTPUT
        echo "date=$(date +'%d_%m_%Y')" >> $GITHUB_OUTPUT

    - name: Создать релиз на GitHub
      uses: softprops/action-gh-release@v2
      with:
        tag_name: Сборка-${{ steps.ids.outputs.date }}
        name: "Сборка от ${{ steps.ids.outputs.date }}"
        body: "Автоматическая сборка для коммита ${{ github.sha }}"
        files: |
          AOSP_*.zip
          MIUI_*.zip
        if-no-files-found: error
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
